src/RazorPagesProject/Pages/About.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace RazorPagesProject.Pages
{
    public class AboutModel : PageModel
    {
        public string Message { get; set; }

        public void OnGet()
        {
            Message = "Your application description page.";
        }
    }
}

src/RazorPagesProject/Pages/Contact.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace RazorPagesProject.Pages
{
    public class ContactModel : PageModel
    {
        public string Message { get; set; }

        public void OnGet()
        {
            Message = "Your contact page.";
        }
    }
}

src/RazorPagesProject/Pages/Error.cshtml.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace RazorPagesProject.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

src/RazorPagesProject/Pages/GithubProfile.cshtml.cs
using System.ComponentModel.DataAnnotations;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using RazorPagesProject.Services;

namespace RazorPagesProject.Pages
{
    public class GithubProfileModel : PageModel
    {
        public GithubProfileModel(IGithubClient client)
        {
            Client = client;
        }

        public class InputModel
        {
            [Required]
            public string UserName { get; set; }
        }

        [BindProperty]
        public InputModel Input { get; set; }

        public IGithubClient Client { get; }

        public GithubUser GithubUser { get; private set; }

        public async Task<IActionResult> OnGetAsync([FromRoute] string userName)
        {
            if (userName != null)
            {
                GithubUser = await Client.GetUserAsync(userName);
            }

            return Page();
        }

        public IActionResult OnPost()
        {
            if (string.IsNullOrEmpty(Input.UserName))
            {
                return Page();
            }

            return RedirectToPage(new { Input.UserName });
        }
    }
}

src/RazorPagesProject/Pages/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using RazorPagesProject.Data;
using RazorPagesProject.Services;

namespace RazorPagesProject.Pages
{
    // <snippet1>
    public class IndexModel : PageModel
    {
        private readonly ApplicationDbContext _db;
        private readonly IQuoteService _quoteService;

        public IndexModel(ApplicationDbContext db, IQuoteService quoteService)
        {
            _db = db;
            _quoteService = quoteService;
        }

        [BindProperty]
        public Message Message { get; set; }

        public IList<Message> Messages { get; private set; }

        [TempData]
        public string MessageAnalysisResult { get; set; }

        public string Quote { get; private set; }

        public async Task OnGetAsync()
        {
            Messages = await _db.GetMessagesAsync();

            Quote = await _quoteService.GenerateQuote();
        }
        // </snippet1>

        public async Task<IActionResult> OnPostAddMessageAsync()
        {
            if (!ModelState.IsValid)
            {
                Messages = await _db.GetMessagesAsync();

                return Page();
            }

            await _db.AddMessageAsync(Message);

            return RedirectToPage();
        }

        public async Task<IActionResult> OnPostDeleteAllMessagesAsync()
        {
            await _db.DeleteAllMessagesAsync();

            return RedirectToPage();
        }

        public async Task<IActionResult> OnPostDeleteMessageAsync(int id)
        {
            await _db.DeleteMessageAsync(id);

            return RedirectToPage();
        }

        public async Task<IActionResult> OnPostAnalyzeMessagesAsync()
        {
            Messages = await _db.GetMessagesAsync();

            if (Messages.Count == 0)
            {
                MessageAnalysisResult = "There are no messages to analyze.";
            }
            else
            {
                var wordCount = 0;

                foreach (var message in Messages)
                {
                    wordCount += message.Text.Split(' ').Length;
                }

                var avgWordCount = Decimal.Divide(wordCount, Messages.Count);
                MessageAnalysisResult = $"The average message length is {avgWordCount:0.##} words.";
            }

            return RedirectToPage();
        }
    }
}

src/RazorPagesProject/Pages/Privacy.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace RazorPagesProject.Pages
{
    public class PrivacyModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

src/RazorPagesProject/Pages/SecurePage.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace RazorPagesProject.Pages
{
    public class SecurePageModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

src/RazorPagesProject/Pages/About.cshtml
@page
@model AboutModel
@{
    ViewData["Title"] = "About";
}

<h1>@ViewData["Title"]</h1>
<h2>@Model.Message</h2>

<p>Use this area to provide additional information.</p>

src/RazorPagesProject/Pages/Contact.cshtml
@page
@model ContactModel
@{
    ViewData["Title"] = "Contact";
}

<h1>@ViewData["Title"]</h1>
<h2>@Model.Message</h2>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

src/RazorPagesProject/Pages/GithubProfile.cshtml
@page "{userName?}"
@model GithubProfileModel
@{
    ViewData["Title"] = "Github Profile";
}

<h1>GithubProfile</h1>

<form id="user-profile" method="post">
    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title">Introduce a Github user name</h3>
        </div>
        <div class="panel-body">
            <div asp-validation-summary="All" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Input.UserName"></label>
                <input asp-for="Input.UserName" class="form-control" />
                <span asp-validation-for="Input.UserName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <button type="submit" class="btn btn-default">Show user profile!</button>
            </div>
        </div>
    </div>
</form>

@if (Model.GithubUser != null)
{
    <label for="user-login" style="font-weight:bold">Login</label>
    <p id="user-login">@Model.GithubUser.Login</p>
    <label for="name" style="font-weight:bold">Name</label>
    <p id="name">@Model.GithubUser.Name</p>
    <label for="company" style="font-weight:bold">Company</label>
    <p id="company">@Model.GithubUser.Company</p>
}

src/RazorPagesProject/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Message System";
}

<h1>@ViewData["Title"]</h1>

<!-- <snippet_Quote> -->
<input id="quote" type="hidden" value="@Model.Quote">
<!-- </snippet_Quote> -->

<form id="addMessage" method="post">
    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title">Add a message</h3>
        </div>
        <div class="panel-body">
            <div class="form-group">
                <label asp-for="Message.Text"></label>
                <input asp-for="Message.Text" class="form-control" style="width:100%">
                <span asp-validation-for="Message.Text" class="text-danger"></span>
            </div>
            <div class="form-group">
                <button id="addMessageBtn" type="submit" asp-page-handler="AddMessage" class="btn btn-default">Add Message</button>
            </div>
        </div>
    </div>
</form>

<form id="messages" method="post">
    <div class="panel panel-default">
        <div class="panel-heading clearfix">
            <button id="deleteAllBtn" type="submit" asp-page-handler="DeleteAllMessages" class="pull-right btn btn-danger">Clear All</button>
            <h3 class="panel-title" style="line-height:2.1">Messages</h3>
        </div>
        <div class="panel-body">
            <ul>
                @foreach (var message in Model.Messages)
                {
                    <li style="line-height:2.5">
                        <button id="deleteBtn@(message.Id)" type="submit" class="btn btn-danger" style="margin-bottom:2px" asp-page-handler="DeleteMessage" asp-route-id="@message.Id">Delete</button>
                        @message.Text
                    </li>
                }
            </ul>
        </div>
    </div>
</form>

<form id="analyze" method="post">
    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title">Analyze Messages</h3>
        </div>
        <div class="panel-body">
            <div class="form-group">
                <button id="analyzeBtn" type="submit" asp-page-handler="AnalyzeMessages" class="btn btn-default">Analyze</button>
            </div>
            <div class="form-group">
                @Model.MessageAnalysisResult
            </div>
        </div>
    </div>
</form>

src/RazorPagesProject/Pages/SecurePage.cshtml
@page
@model SecurePageModel
@{
    ViewData["Title"] = "Secure Page";
}

<h1>@ViewData["Title"]</h1>

<p>This is a secure page in the app.</p>